name: FKBAmongUs
main: io.github.FKB.FKBAmongUs.Main
version: 1.0
api-version: 1.13
commands:
   hi:
      description: This is a demo command.
      usage: /hi
      permission: FKBAmongUs.hi
      permission-message: You don't have <permission>
   FKBAmongUs:
      description: This is a handler command for the event.
      usage: /FKBAmongUs <join>
      permission: FKBAmongUs.join
      permission-message: You don't have <permission>
      
permissions:
    FKBAmongUs.*:
        description: gives help to use FKBAmongUs.
        default: op
        children:
        FKBAmongUs.join: true
        FKBAmongUs.leave: true
        FKBAmongUs.list: true
        FKBAmongUs.start: false
        FKBAmongUs.stop: false
        FKBAmongUs.setLobby: false
        FKBAmongUs.setmaxplayers: false
        FKBAmongUs.setminplayers: false
        FKBAmongUs.setnumberimpostors: false
        FKBAmongUs.setmeetingtime: false
        FKBAmongUs.setvotingtime: false
    FKBAmongUs.join:
        description: join a match.
        default: true
    FKBAmongUs.leave:
        description: leave for the match.
        default: true
    FKBAmongUs.list:
        description: Show list of players in game.
        default: true
    FKBAmongUs.start:
        description: start the game.
        default: false
    FKBAmongUs.stop:
        description: stop the game.
        default: false
    FKBAmongUs.setLobby:
        description: Set the lobby of the game.
        default: false
    FKBAmongUs.setmaxplayers:
        description: Set number maximum players
        default: false
    FKBAmongUs.setminplayers:
        description: Set number minimum players
        default: false
    FKBAmongUs.setnumberimpostors:
        description: Set number of impostors
        default: false
    FKBAmongUs.setmeetingtime:
        description: Set time to talk
        default: false
    FKBAmongUs.setvotingtime:
        description: Set time to vote
        default: false
        